### ISSUE TITLE
$AZURE_CONTAINERAPPS_ENV_DEFAULT_DOMAIN can not be applied

### ISSUE THREAD

**Issue by vienleidl** [smurawski/docker-compose-examples#4]
After run the _az containercompose create_ command with the following docker-compose file, the value of SERVER_HOST environment var hasn't been applied correctly. The result is SERVER_HOST => **nginx.** in Container App's environment variables.

```
version: '3.4'
services:
  app:
    image: 'ACR_NAME.azurecr.io/Repo_Name/Image_Name:Tag_Name'
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - SERVER_PROTOCOL=HTTP
      - SERVER_HOST=nginx.$AZURE_CONTAINERAPPS_ENV_DEFAULT_DOMAIN
      - SERVER_PORT=80
      - SERVER_PATH=/app

```

If it's updated as nginx.$$AZURE_CONTAINERAPPS_ENV_DEFAULT_DOMAIN => the result will be SERVER_HOST => nginx.$
